# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_desp_cartao_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 640)
        MainWindow.setStyleSheet("\n"
"QMainWindow{\n"
" background:#f6f8fb;\n"
"}\n"
"\n"
"QFrame{\n"
" background:white;\n"
" border:1px solid #e5e7eb;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QLabel#title{\n"
" font-size:20px;\n"
" font-weight:600;\n"
"}\n"
"\n"
"QLineEdit,QComboBox,QSpinBox,QDoubleSpinBox,QDateEdit{\n"
" border:1px solid #d1d5db;\n"
" border-radius:6px;\n"
" padding:6px;\n"
" background:white;\n"
" min-height:28px;\n"
"}\n"
"\n"
"QPushButton{\n"
" background:#2563eb;\n"
" color:white;\n"
" border-radius:6px;\n"
" padding:6px 14px;\n"
" font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background:#1d4ed8;\n"
"}\n"
"\n"
"QTableView{\n"
" border:none;\n"
" background:white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.headerCard = QtWidgets.QFrame(self.centralwidget)
        self.headerCard.setObjectName("headerCard")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.headerCard)
        self.hboxlayout.setObjectName("hboxlayout")
        self.titleLabel = QtWidgets.QLabel(self.headerCard)
        self.titleLabel.setObjectName("titleLabel")
        self.hboxlayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.combo_Banco = QtWidgets.QComboBox(self.headerCard)
        self.combo_Banco.setObjectName("combo_Banco")
        self.hboxlayout.addWidget(self.combo_Banco)
        self.combo_Fatura = QtWidgets.QComboBox(self.headerCard)
        self.combo_Fatura.setObjectName("combo_Fatura")
        self.hboxlayout.addWidget(self.combo_Fatura)
        self.date_Emissao = QtWidgets.QDateEdit(self.headerCard)
        self.date_Emissao.setObjectName("date_Emissao")
        self.hboxlayout.addWidget(self.date_Emissao)
        self.mainLayout.addWidget(self.headerCard)
        self.bodyLayout = QtWidgets.QHBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.cardLancamento = QtWidgets.QFrame(self.centralwidget)
        self.cardLancamento.setObjectName("cardLancamento")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.cardLancamento)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label = QtWidgets.QLabel(self.cardLancamento)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.label1 = QtWidgets.QLabel(self.cardLancamento)
        self.label1.setObjectName("label1")
        self.vboxlayout1.addWidget(self.label1)
        self.line_busca_estabelecimento = QtWidgets.QLineEdit(self.cardLancamento)
        self.line_busca_estabelecimento.setObjectName("line_busca_estabelecimento")
        self.vboxlayout1.addWidget(self.line_busca_estabelecimento)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label2 = QtWidgets.QLabel(self.cardLancamento)
        self.label2.setObjectName("label2")
        self.gridlayout.addWidget(self.label2, 0, 0, 1, 1)
        self.combo_Categoria = QtWidgets.QComboBox(self.cardLancamento)
        self.combo_Categoria.setObjectName("combo_Categoria")
        self.gridlayout.addWidget(self.combo_Categoria, 0, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(self.cardLancamento)
        self.label3.setObjectName("label3")
        self.gridlayout.addWidget(self.label3, 1, 0, 1, 1)
        self.combo_Cidade = QtWidgets.QComboBox(self.cardLancamento)
        self.combo_Cidade.setObjectName("combo_Cidade")
        self.gridlayout.addWidget(self.combo_Cidade, 1, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.cardLancamento)
        self.label4.setObjectName("label4")
        self.gridlayout.addWidget(self.label4, 2, 0, 1, 1)
        self.spin_Valor = QtWidgets.QDoubleSpinBox(self.cardLancamento)
        self.spin_Valor.setMaximum(9999999.0)
        self.spin_Valor.setObjectName("spin_Valor")
        self.gridlayout.addWidget(self.spin_Valor, 2, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(self.cardLancamento)
        self.label5.setObjectName("label5")
        self.gridlayout.addWidget(self.label5, 3, 0, 1, 1)
        self.spin_Parcelas = QtWidgets.QSpinBox(self.cardLancamento)
        self.spin_Parcelas.setObjectName("spin_Parcelas")
        self.gridlayout.addWidget(self.spin_Parcelas, 3, 1, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.label6 = QtWidgets.QLabel(self.cardLancamento)
        self.label6.setObjectName("label6")
        self.vboxlayout1.addWidget(self.label6)
        self.plain_Obs = QtWidgets.QPlainTextEdit(self.cardLancamento)
        self.plain_Obs.setMaximumHeight(70)
        self.plain_Obs.setObjectName("plain_Obs")
        self.vboxlayout1.addWidget(self.plain_Obs)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.btn_Limpar = QtWidgets.QPushButton(self.cardLancamento)
        self.btn_Limpar.setObjectName("btn_Limpar")
        self.hboxlayout1.addWidget(self.btn_Limpar)
        self.btn_Salvar = QtWidgets.QPushButton(self.cardLancamento)
        self.btn_Salvar.setObjectName("btn_Salvar")
        self.hboxlayout1.addWidget(self.btn_Salvar)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.vboxlayout.addWidget(self.cardLancamento)
        self.cardSugestoes = QtWidgets.QFrame(self.centralwidget)
        self.cardSugestoes.setObjectName("cardSugestoes")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.cardSugestoes)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label7 = QtWidgets.QLabel(self.cardSugestoes)
        self.label7.setObjectName("label7")
        self.vboxlayout2.addWidget(self.label7)
        self.table_Sugestoes = QtWidgets.QTableView(self.cardSugestoes)
        self.table_Sugestoes.setObjectName("table_Sugestoes")
        self.vboxlayout2.addWidget(self.table_Sugestoes)
        self.vboxlayout.addWidget(self.cardSugestoes)
        self.bodyLayout.addLayout(self.vboxlayout)
        self.cardHistorico = QtWidgets.QFrame(self.centralwidget)
        self.cardHistorico.setObjectName("cardHistorico")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.cardHistorico)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.label8 = QtWidgets.QLabel(self.cardHistorico)
        self.label8.setObjectName("label8")
        self.vboxlayout3.addWidget(self.label8)
        self.table_Historico = QtWidgets.QTableView(self.cardHistorico)
        self.table_Historico.setObjectName("table_Historico")
        self.vboxlayout3.addWidget(self.table_Historico)
        self.bodyLayout.addWidget(self.cardHistorico)
        self.mainLayout.addLayout(self.bodyLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Finflux - Lançar Despesa Cartão"))
        self.titleLabel.setText(_translate("MainWindow", "💳 Lançar Despesa no Cartão"))
        self.label.setText(_translate("MainWindow", "Lançamento rápido"))
        self.label.setStyleSheet(_translate("MainWindow", "font-weight:600;"))
        self.label1.setText(_translate("MainWindow", "🔎 Estabelecimento"))
        self.line_busca_estabelecimento.setPlaceholderText(_translate("MainWindow", "Digite para pesquisar estabelecimento..."))
        self.label2.setText(_translate("MainWindow", "Categoria"))
        self.label3.setText(_translate("MainWindow", "Cidade"))
        self.label4.setText(_translate("MainWindow", "Valor"))
        self.label5.setText(_translate("MainWindow", "Parcelas"))
        self.label6.setText(_translate("MainWindow", "Observação"))
        self.btn_Limpar.setText(_translate("MainWindow", "Limpar"))
        self.btn_Salvar.setText(_translate("MainWindow", "Salvar"))
        self.label7.setText(_translate("MainWindow", "Sugestões inteligentes"))
        self.label7.setStyleSheet(_translate("MainWindow", "font-weight:600;"))
        self.label8.setText(_translate("MainWindow", "Últimos lançamentos"))
        self.label8.setStyleSheet(_translate("MainWindow", "font-weight:600;"))
